name: Build & Push Docker Image    
    
on:    
  # 手动触发  
  workflow_dispatch:  
    inputs:  
      tag:  
        description: 'Docker 标签'  
        required: false  
        default: 'latest'  
        type: string  
  # 自动触发 - 推送到主分支  
  push:    
    branches: [ main, master ]  
    paths:  
      - 'vod.js'  
      - 'package.json'  
      - 'Dockerfile'  
      - '.github/workflows/docker-image.yml'  
    
permissions:    
  contents: read    
  packages: write    
    
jobs:    
  build:    
    runs-on: ubuntu-latest    
    steps:    
      - uses: actions/checkout@v4    
          
      - name: Login to GitHub Container Registry    
        uses: docker/login-action@v3    
        with:    
          registry: ghcr.io    
          username: ${{ github.actor }}    
          password: ${{ secrets.GITHUB_TOKEN }}    
          
      - name: Set lowercase owner    
        id: lowercase    
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"    
          
      - name: Build and push    
        uses: docker/build-push-action@v5    
        with:    
          context: .    
          push: true    
          tags: ghcr.io/${{ steps.lowercase.outputs.owner }}/vod:latest    
          platforms: linux/amd64
